# Generated by Django 5.2.9 on 2026-01-07 23:44

import ai_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=ai_api.models.document_upload_path),
        ),
    ]
