# Generated by Django 5.2.9 on 2026-01-09 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0002_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgyptianLaw',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(blank=True, null=True)),
                ('seeded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Egyptian Law',
                'verbose_name_plural': 'Egyptian Laws',
                'ordering': ['title_en'],
            },
        ),
        migrations.CreateModel(
            name='EgyptianLawChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_api.egyptianlaw')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='LawChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='ai_api.egyptianlaw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LawChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_api.lawchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
